// AAVE V2
export { getAaveAdjustDownV2OperationDefinition } from './aave/v2/adjust-down'
export { getAaveAdjustUpV2OperationDefinition } from './aave/v2/adjust-up'
export { getAaveBorrowV2OperationDefinition } from './aave/v2/borrow'
export { getAaveCloseV2OperationDefinition } from './aave/v2/close'
export { getAaveDepositV2OperationDefinition } from './aave/v2/deposit'
export { getAaveDepositBorrowV2OperationDefinition } from './aave/v2/deposit-borrow'
export { getAaveOpenV2OperationDefinition } from './aave/v2/open'
export { getAavePaybackWithdrawV2OperationDefinition } from './aave/v2/payback-withdraw'

// AAVE V3
export { getAaveAdjustDownV3OperationDefinition } from './aave/v3/adjust-down'
export { getAaveAdjustUpV3OperationDefinition } from './aave/v3/adjust-up'
export { getAaveBorrowV3OperationDefinition } from './aave/v3/borrow'
export { getAaveV3CloseAndExitOperationDefinition } from './aave/v3/close-and-exit'
export { getAaveV3CloseAndRemainOperationDefinition } from './aave/v3/close-and-remain'
export { getAaveDepositV3OperationDefinition } from './aave/v3/deposit'
export { getAaveDepositBorrowV3OperationDefinition } from './aave/v3/deposit-borrow'
export { getAaveOpenV3OperationDefinition } from './aave/v3/open'
export { getAaveOpenDepositBorrowV3OperationDefinition } from './aave/v3/open-deposit-borrow'
export { getAavePaybackWithdrawV3OperationDefinition } from './aave/v3/payback-withdraw'
export { getAaveV3WithdrawOperationDefinition } from './aave/v3/withdraw'
export { getAaveV3WithdrawToDebtOperationDefinition } from './aave/v3/withdraw-to-debt'

// AJNA
export { getAjnaAdjustDownOperationDefinition } from './ajna/adjust-down'
export { getAjnaAdjustUpOperationDefinition } from './ajna/adjust-up'
export { getAjnaCloseToCollateralOperationDefinition } from './ajna/close-to-collateral'
export { getAjnaCloseToQuoteOperationDefinition } from './ajna/close-to-quote'
export { getAjnaOpenOperationDefinition } from './ajna/open'

// SPARK
export { getSparkBorrowOperationDefinition } from './spark/borrow'
export { getSparkDepositOperationDefinition } from './spark/borrow'
export { getSparkDepositBorrowOperationDefinition } from './spark/borrow'
export { getSparkOpenDepositBorrowOperationDefinition } from './spark/borrow'
export { getSparkPaybackWithdrawOperationDefinition } from './spark/borrow'
export { getSparkWithdrawOperationDefinition } from './spark/auto/withdraw'
export { getSparkWithdrawToDebtOperationDefinition } from './spark/auto/withdraw-to-debt'
export { getSparkOpenOperationDefinition } from './spark/multiply'
export { getSparkCloseAndExitOperationDefinition } from './spark/multiply'
export { getSparkCloseAndRemainOperationDefinition } from './spark/multiply'
export { getSparkAdjustDownOperationDefinition } from './spark/multiply'
export { getSparkAdjustUpOperationDefinition } from './spark/multiply'

// MORPHO BLUE
export { getMorphoBlueBorrowOperationDefinition } from './morphoblue/borrow'
export { getMorphoBlueDepositOperationDefinition } from './morphoblue/borrow'
export { getMorphoBlueDepositBorrowOperationDefinition } from './morphoblue/borrow'
export { getMorphoBlueOpenDepositBorrowOperationDefinition } from './morphoblue/borrow'
export { getMorphoBluePaybackWithdrawOperationDefinition } from './morphoblue/borrow'
export { getMorphoBlueOpenOperationDefinition } from './morphoblue/multiply'
export { getMorphoBlueCloseOperationDefinition } from './morphoblue/multiply'
export { getMorphoBlueCloseAndRemainOperationDefinition } from './morphoblue/multiply'
export { getMorphoBlueAdjustDownOperationDefinition } from './morphoblue/multiply'
export { getMorphoBlueAdjustUpOperationDefinition } from './morphoblue/multiply'
export { getMorphoBlueWithdrawOperationDefinition } from './morphoblue/auto/withdraw'
export { getMorphoBlueWithdrawToDebtOperationDefinition } from './morphoblue/auto/withdraw-to-debt'

// COMMON
export { getErc4626DepositOperationDefinition } from './common/erc4626'
export { getErc4626WithdrawOperationDefinition } from './common/erc4626'
